# Generated by Django 6.0.2 on 2026-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='placa_veiculo',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
