# Generated by Django 6.0.2 on 2026-02-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_cliente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
