# Generated by Django 6.0.2 on 2026-02-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='setor',
            field=models.CharField(choices=[('DS', 'DS'), ('DA', 'DA'), ('DT', 'DT'), ('CPD', 'CPD'), ('DIPAP', 'DIPAP'), ('COPAM', 'COPAM'), ('CSG', 'CSG'), ('DIFAU', 'DIFAU'), ('CPL', 'CPL'), ('PROJUR', 'PROJUR'), ('CRH', 'CRH'), ('ASPLAN', 'ASPLAN'), ('DIAT', 'DIAT'), ('CCF', 'CCF'), ('CCA', 'CCA'), ('DIMIN', 'DIMIN'), ('DINFRA', 'DINFRA'), ('COMEG', 'COMEG'), ('SRS', 'SRS'), ('SUDCAR', 'SUDCAR'), ('CEA', 'CEA'), ('DAO', 'DAO'), ('ASCOM', 'ASCOM'), ('DIFLOR', 'DIFLOR'), ('SETGEO', 'SETGEO'), ('CAEIA', 'CAEIA'), ('NOC', 'NOC'), ('Outros', 'Outros')], default='Outros', max_length=15),
        ),
    ]
