# Generated by Django 6.0.2 on 2026-02-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0006_alter_cliente_setor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="modelo_veiculo",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="placa_veiculo",
        ),
    ]
