# Generated by Django 6.0.2 on 2026-02-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0007_remove_cliente_modelo_veiculo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="setor",
            field=models.CharField(
                choices=[
                    ("Selecione", "Selecione"),
                    ("ASCOM", "ASCOM"),
                    ("ASPLAN", "ASPLAN"),
                    ("CAEIA", "CAEIA"),
                    ("CCA", "CCA"),
                    ("CCF", "CCF"),
                    ("CEA", "CEA"),
                    ("CMA", "CMA"),
                    ("COMEG", "COMEG"),
                    ("COPAM", "COPAM"),
                    ("CPD", "CPD"),
                    ("CPL", "CPL"),
                    ("CRH", "CRH"),
                    ("CSG", "CSG"),
                    ("DA", "DA"),
                    ("DAO", "DAO"),
                    ("DIAT", "DIAT"),
                    ("DIFAU", "DIFAU"),
                    ("DIFLOR", "DIFLOR"),
                    ("DIMIN", "DIMIN"),
                    ("DINFRA", "DINFRA"),
                    ("DIPAP", "DIPAP"),
                    ("DS", "DS"),
                    ("DT", "DT"),
                    ("NOC", "NOC"),
                    ("PROJUR", "PROJUR"),
                    ("SETGEO", "SETGEO"),
                    ("SRS", "SRS"),
                    ("SUDCAR", "SUDCAR"),
                ],
                default="Selecione",
                max_length=15,
            ),
        ),
    ]
